/** Auto-generated by syncFigmaIconManifest.js — lucide */
/** Catalog: 50 icons from Figma · Assets on disk: 50 */

import icon_ambulance from '../../../assets/icons/lucide/ambulance.svg'
import icon_arrow_down_to_line from '../../../assets/icons/lucide/arrow-down-to-line.svg'
import icon_badge_check from '../../../assets/icons/lucide/badge-check.svg'
import icon_badge_check_bold from '../../../assets/icons/lucide/badge-check-bold.svg'
import icon_ban from '../../../assets/icons/lucide/ban.svg'
import icon_book_check from '../../../assets/icons/lucide/book-check.svg'
import icon_book_open_check from '../../../assets/icons/lucide/book-open-check.svg'
import icon_book_user from '../../../assets/icons/lucide/book-user.svg'
import icon_bot from '../../../assets/icons/lucide/bot.svg'
import icon_brain from '../../../assets/icons/lucide/brain.svg'
import icon_briefcase_business from '../../../assets/icons/lucide/briefcase-business.svg'
import icon_chart_no_axes_column_increasing from '../../../assets/icons/lucide/chart-no-axes-column-increasing.svg'
import icon_chart_no_axes_combined from '../../../assets/icons/lucide/chart-no-axes-combined.svg'
import icon_check from '../../../assets/icons/lucide/check.svg'
import icon_chevron_down from '../../../assets/icons/lucide/chevron-down.svg'
import icon_chevron_up from '../../../assets/icons/lucide/chevron-up.svg'
import icon_chevrons_left from '../../../assets/icons/lucide/chevrons-left.svg'
import icon_chevrons_right from '../../../assets/icons/lucide/chevrons-right.svg'
import icon_clipboard_check from '../../../assets/icons/lucide/clipboard-check.svg'
import icon_clipboard_copy from '../../../assets/icons/lucide/clipboard-copy.svg'
import icon_clipboard_x from '../../../assets/icons/lucide/clipboard-x.svg'
import icon_clock_alert from '../../../assets/icons/lucide/clock-alert.svg'
import icon_excel from '../../../assets/icons/lucide/excel.svg'
import icon_file_minus from '../../../assets/icons/lucide/file-minus.svg'
import icon_file_plus from '../../../assets/icons/lucide/file-plus.svg'
import icon_file_stack from '../../../assets/icons/lucide/file-stack.svg'
import icon_file_text from '../../../assets/icons/lucide/file-text.svg'
import icon_grid_2x2 from '../../../assets/icons/lucide/grid-2x2.svg'
import icon_handshake from '../../../assets/icons/lucide/handshake.svg'
import icon_heart_pulse from '../../../assets/icons/lucide/heart-pulse.svg'
import icon_hired from '../../../assets/icons/lucide/hired.svg'
import icon_hospital from '../../../assets/icons/lucide/hospital.svg'
import icon_image from '../../../assets/icons/lucide/image.svg'
import icon_images from '../../../assets/icons/lucide/images.svg'
import icon_mail from '../../../assets/icons/lucide/mail.svg'
import icon_mail_open from '../../../assets/icons/lucide/mail-open.svg'
import icon_medal from '../../../assets/icons/lucide/medal.svg'
import icon_minimize from '../../../assets/icons/lucide/minimize.svg'
import icon_paperclip from '../../../assets/icons/lucide/paperclip.svg'
import icon_pickaxe from '../../../assets/icons/lucide/pickaxe.svg'
import icon_picture_in_picture_2 from '../../../assets/icons/lucide/picture-in-picture-2.svg'
import icon_rocket from '../../../assets/icons/lucide/rocket.svg'
import icon_sparkles from '../../../assets/icons/lucide/sparkles.svg'
import icon_square_menu from '../../../assets/icons/lucide/square-menu.svg'
import icon_toggle_left from '../../../assets/icons/lucide/toggle-left.svg'
import icon_upload from '../../../assets/icons/lucide/upload.svg'
import icon_user_round_pen from '../../../assets/icons/lucide/user-round-pen.svg'
import icon_wifi from '../../../assets/icons/lucide/wifi.svg'
import icon_wifi_high from '../../../assets/icons/lucide/wifi-high.svg'
import icon_wifi_off from '../../../assets/icons/lucide/wifi-off.svg'

export const lucideRegistry = {
  'ambulance': icon_ambulance,
  'arrow-down-to-line': icon_arrow_down_to_line,
  'badge-check': icon_badge_check,
  'badge-check-bold': icon_badge_check_bold,
  'ban': icon_ban,
  'book-check': icon_book_check,
  'book-open-check': icon_book_open_check,
  'book-user': icon_book_user,
  'bot': icon_bot,
  'brain': icon_brain,
  'briefcase-business': icon_briefcase_business,
  'chart-no-axes-column-increasing': icon_chart_no_axes_column_increasing,
  'chart-no-axes-combined': icon_chart_no_axes_combined,
  'check': icon_check,
  'chevron-down': icon_chevron_down,
  'chevron-up': icon_chevron_up,
  'chevrons-left': icon_chevrons_left,
  'chevrons-right': icon_chevrons_right,
  'clipboard-check': icon_clipboard_check,
  'clipboard-copy': icon_clipboard_copy,
  'clipboard-x': icon_clipboard_x,
  'clock-alert': icon_clock_alert,
  'excel': icon_excel,
  'file-minus': icon_file_minus,
  'file-plus': icon_file_plus,
  'file-stack': icon_file_stack,
  'file-text': icon_file_text,
  'grid-2x2': icon_grid_2x2,
  'handshake': icon_handshake,
  'heart-pulse': icon_heart_pulse,
  'hired': icon_hired,
  'hospital': icon_hospital,
  'image': icon_image,
  'images': icon_images,
  'mail': icon_mail,
  'mail-open': icon_mail_open,
  'medal': icon_medal,
  'minimize': icon_minimize,
  'paperclip': icon_paperclip,
  'pickaxe': icon_pickaxe,
  'picture-in-picture-2': icon_picture_in_picture_2,
  'rocket': icon_rocket,
  'sparkles': icon_sparkles,
  'square-menu': icon_square_menu,
  'toggle-left': icon_toggle_left,
  'upload': icon_upload,
  'user-round-pen': icon_user_round_pen,
  'wifi': icon_wifi,
  'wifi-high': icon_wifi_high,
  'wifi-off': icon_wifi_off,
} as const

export type LucideIconName = keyof typeof lucideRegistry
