/** Auto-generated by syncFigmaIconManifest.js — tabler */
/** Catalog: 114 icons from Figma · Assets on disk: 114 */

import icon_alert_circle from '../../../assets/icons/tabler/alert-circle.svg'
import icon_arrow_bar_to_down from '../../../assets/icons/tabler/arrow-bar-to-down.svg'
import icon_arrow_bar_up from '../../../assets/icons/tabler/arrow-bar-up.svg'
import icon_arrow_right from '../../../assets/icons/tabler/arrow-right.svg'
import icon_award from '../../../assets/icons/tabler/award.svg'
import icon_backhoe from '../../../assets/icons/tabler/backhoe.svg'
import icon_behance from '../../../assets/icons/tabler/behance.svg'
import icon_blockquote from '../../../assets/icons/tabler/blockquote.svg'
import icon_bold from '../../../assets/icons/tabler/bold.svg'
import icon_bookmark from '../../../assets/icons/tabler/bookmark.svg'
import icon_bookmark_plus from '../../../assets/icons/tabler/bookmark-plus.svg'
import icon_brand_facebook from '../../../assets/icons/tabler/brand-facebook.svg'
import icon_brand_instagram from '../../../assets/icons/tabler/brand-instagram.svg'
import icon_brand_linkedin from '../../../assets/icons/tabler/brand-linkedin.svg'
import icon_brand_tiktok from '../../../assets/icons/tabler/brand-tiktok.svg'
import icon_brand_twitter from '../../../assets/icons/tabler/brand-twitter.svg'
import icon_brand_whatsapp from '../../../assets/icons/tabler/brand-whatsapp.svg'
import icon_brand_youtube from '../../../assets/icons/tabler/brand-youtube.svg'
import icon_brief from '../../../assets/icons/tabler/brief.svg'
import icon_brush from '../../../assets/icons/tabler/brush.svg'
import icon_building from '../../../assets/icons/tabler/building.svg'
import icon_building_skyscraper from '../../../assets/icons/tabler/building-skyscraper.svg'
import icon_bulb from '../../../assets/icons/tabler/bulb.svg'
import icon_calendar_event from '../../../assets/icons/tabler/calendar-event.svg'
import icon_calendar_time from '../../../assets/icons/tabler/calendar-time.svg'
import icon_certificate from '../../../assets/icons/tabler/certificate.svg'
import icon_check from '../../../assets/icons/tabler/check.svg'
import icon_checks from '../../../assets/icons/tabler/checks.svg'
import icon_circle from '../../../assets/icons/tabler/circle.svg'
import icon_circle_minus from '../../../assets/icons/tabler/circle-minus.svg'
import icon_circle_square from '../../../assets/icons/tabler/circle-square.svg'
import icon_click from '../../../assets/icons/tabler/click.svg'
import icon_clock from '../../../assets/icons/tabler/clock.svg'
import icon_close from '../../../assets/icons/tabler/close.svg'
import icon_cloud_upload from '../../../assets/icons/tabler/cloud-upload.svg'
import icon_coin from '../../../assets/icons/tabler/coin.svg'
import icon_copy from '../../../assets/icons/tabler/copy.svg'
import icon_corner_down_left_double from '../../../assets/icons/tabler/corner-down-left-double.svg'
import icon_corner_down_right_double from '../../../assets/icons/tabler/corner-down-right-double.svg'
import icon_cpu from '../../../assets/icons/tabler/cpu.svg'
import icon_current_location from '../../../assets/icons/tabler/current-location.svg'
import icon_disabled from '../../../assets/icons/tabler/disabled.svg'
import icon_eye from '../../../assets/icons/tabler/eye.svg'
import icon_eye_off from '../../../assets/icons/tabler/eye-off.svg'
import icon_file_certificate from '../../../assets/icons/tabler/file-certificate.svg'
import icon_file_check from '../../../assets/icons/tabler/file-check.svg'
import icon_file_download from '../../../assets/icons/tabler/file-download.svg'
import icon_file_export from '../../../assets/icons/tabler/file-export.svg'
import icon_file_spreadsheet from '../../../assets/icons/tabler/file-spreadsheet.svg'
import icon_file_text from '../../../assets/icons/tabler/file-text.svg'
import icon_file_upload from '../../../assets/icons/tabler/file-upload.svg'
import icon_friends from '../../../assets/icons/tabler/friends.svg'
import icon_handler from '../../../assets/icons/tabler/handler.svg'
import icon_headset from '../../../assets/icons/tabler/headset.svg'
import icon_history from '../../../assets/icons/tabler/history.svg'
import icon_id from '../../../assets/icons/tabler/id.svg'
import icon_italic from '../../../assets/icons/tabler/italic.svg'
import icon_language from '../../../assets/icons/tabler/language.svg'
import icon_link from '../../../assets/icons/tabler/link.svg'
import icon_list from '../../../assets/icons/tabler/list.svg'
import icon_list_check from '../../../assets/icons/tabler/list-check.svg'
import icon_list_numbers from '../../../assets/icons/tabler/list-numbers.svg'
import icon_mail from '../../../assets/icons/tabler/mail.svg'
import icon_man from '../../../assets/icons/tabler/man.svg'
import icon_map_pin from '../../../assets/icons/tabler/map-pin.svg'
import icon_medal from '../../../assets/icons/tabler/medal.svg'
import icon_mood_kid from '../../../assets/icons/tabler/mood-kid.svg'
import icon_more from '../../../assets/icons/tabler/more.svg'
import icon_pacman from '../../../assets/icons/tabler/pacman.svg'
import icon_palette from '../../../assets/icons/tabler/palette.svg'
import icon_pencil from '../../../assets/icons/tabler/pencil.svg'
import icon_phone from '../../../assets/icons/tabler/phone.svg'
import icon_photo from '../../../assets/icons/tabler/photo.svg'
import icon_play from '../../../assets/icons/tabler/play.svg'
import icon_player_play from '../../../assets/icons/tabler/player-play.svg'
import icon_puzzle from '../../../assets/icons/tabler/puzzle.svg'
import icon_qrcode from '../../../assets/icons/tabler/qrcode.svg'
import icon_question from '../../../assets/icons/tabler/question.svg'
import icon_school from '../../../assets/icons/tabler/school.svg'
import icon_share from '../../../assets/icons/tabler/share.svg'
import icon_smart_home from '../../../assets/icons/tabler/smart-home.svg'
import icon_sort_ascending from '../../../assets/icons/tabler/sort-ascending.svg'
import icon_sort_descending from '../../../assets/icons/tabler/sort-descending.svg'
import icon_speakerphone from '../../../assets/icons/tabler/speakerphone.svg'
import icon_tags from '../../../assets/icons/tabler/tags.svg'
import icon_target_arrow from '../../../assets/icons/tabler/target-arrow.svg'
import icon_trash from '../../../assets/icons/tabler/trash.svg'
import icon_trophy from '../../../assets/icons/tabler/trophy.svg'
import icon_tyipography from '../../../assets/icons/tabler/tyipography.svg'
import icon_underline from '../../../assets/icons/tabler/underline.svg'
import icon_urgent from '../../../assets/icons/tabler/urgent.svg'
import icon_urgent_bold from '../../../assets/icons/tabler/urgent-bold.svg'
import icon_user from '../../../assets/icons/tabler/user.svg'
import icon_user_check from '../../../assets/icons/tabler/user-check.svg'
import icon_user_circle from '../../../assets/icons/tabler/user-circle.svg'
import icon_user_close from '../../../assets/icons/tabler/user-close.svg'
import icon_user_cog from '../../../assets/icons/tabler/user-cog.svg'
import icon_user_exclamation from '../../../assets/icons/tabler/user-exclamation.svg'
import icon_user_off from '../../../assets/icons/tabler/user-off.svg'
import icon_user_pause from '../../../assets/icons/tabler/user-pause.svg'
import icon_user_plus from '../../../assets/icons/tabler/user-plus.svg'
import icon_user_question from '../../../assets/icons/tabler/user-question.svg'
import icon_user_scan from '../../../assets/icons/tabler/user-scan.svg'
import icon_user_search from '../../../assets/icons/tabler/user-search.svg'
import icon_user_square_rounded from '../../../assets/icons/tabler/user-square-rounded.svg'
import icon_user_star from '../../../assets/icons/tabler/user-star.svg'
import icon_users from '../../../assets/icons/tabler/users.svg'
import icon_video from '../../../assets/icons/tabler/video.svg'
import icon_window_maximize from '../../../assets/icons/tabler/window-maximize.svg'
import icon_woman from '../../../assets/icons/tabler/woman.svg'
import icon_world from '../../../assets/icons/tabler/world.svg'
import icon_x from '../../../assets/icons/tabler/x.svg'
import icon_zoom_in from '../../../assets/icons/tabler/zoom-in.svg'
import icon_zoom_out from '../../../assets/icons/tabler/zoom-out.svg'

export const tablerRegistry = {
  'alert-circle': icon_alert_circle,
  'arrow-bar-to-down': icon_arrow_bar_to_down,
  'arrow-bar-up': icon_arrow_bar_up,
  'arrow-right': icon_arrow_right,
  'award': icon_award,
  'backhoe': icon_backhoe,
  'behance': icon_behance,
  'blockquote': icon_blockquote,
  'bold': icon_bold,
  'bookmark': icon_bookmark,
  'bookmark-plus': icon_bookmark_plus,
  'brand-facebook': icon_brand_facebook,
  'brand-instagram': icon_brand_instagram,
  'brand-linkedin': icon_brand_linkedin,
  'brand-tiktok': icon_brand_tiktok,
  'brand-twitter': icon_brand_twitter,
  'brand-whatsapp': icon_brand_whatsapp,
  'brand-youtube': icon_brand_youtube,
  'brief': icon_brief,
  'brush': icon_brush,
  'building': icon_building,
  'building-skyscraper': icon_building_skyscraper,
  'bulb': icon_bulb,
  'calendar-event': icon_calendar_event,
  'calendar-time': icon_calendar_time,
  'certificate': icon_certificate,
  'check': icon_check,
  'checks': icon_checks,
  'circle': icon_circle,
  'circle-minus': icon_circle_minus,
  'circle-square': icon_circle_square,
  'click': icon_click,
  'clock': icon_clock,
  'close': icon_close,
  'cloud-upload': icon_cloud_upload,
  'coin': icon_coin,
  'copy': icon_copy,
  'corner-down-left-double': icon_corner_down_left_double,
  'corner-down-right-double': icon_corner_down_right_double,
  'cpu': icon_cpu,
  'current-location': icon_current_location,
  'disabled': icon_disabled,
  'eye': icon_eye,
  'eye-off': icon_eye_off,
  'file-certificate': icon_file_certificate,
  'file-check': icon_file_check,
  'file-download': icon_file_download,
  'file-export': icon_file_export,
  'file-spreadsheet': icon_file_spreadsheet,
  'file-text': icon_file_text,
  'file-upload': icon_file_upload,
  'friends': icon_friends,
  'handler': icon_handler,
  'headset': icon_headset,
  'history': icon_history,
  'id': icon_id,
  'italic': icon_italic,
  'language': icon_language,
  'link': icon_link,
  'list': icon_list,
  'list-check': icon_list_check,
  'list-numbers': icon_list_numbers,
  'mail': icon_mail,
  'man': icon_man,
  'map-pin': icon_map_pin,
  'medal': icon_medal,
  'mood-kid': icon_mood_kid,
  'more': icon_more,
  'pacman': icon_pacman,
  'palette': icon_palette,
  'pencil': icon_pencil,
  'phone': icon_phone,
  'photo': icon_photo,
  'play': icon_play,
  'player-play': icon_player_play,
  'puzzle': icon_puzzle,
  'qrcode': icon_qrcode,
  'question': icon_question,
  'school': icon_school,
  'share': icon_share,
  'smart-home': icon_smart_home,
  'sort-ascending': icon_sort_ascending,
  'sort-descending': icon_sort_descending,
  'speakerphone': icon_speakerphone,
  'tags': icon_tags,
  'target-arrow': icon_target_arrow,
  'trash': icon_trash,
  'trophy': icon_trophy,
  'tyipography': icon_tyipography,
  'underline': icon_underline,
  'urgent': icon_urgent,
  'urgent-bold': icon_urgent_bold,
  'user': icon_user,
  'user-check': icon_user_check,
  'user-circle': icon_user_circle,
  'user-close': icon_user_close,
  'user-cog': icon_user_cog,
  'user-exclamation': icon_user_exclamation,
  'user-off': icon_user_off,
  'user-pause': icon_user_pause,
  'user-plus': icon_user_plus,
  'user-question': icon_user_question,
  'user-scan': icon_user_scan,
  'user-search': icon_user_search,
  'user-square-rounded': icon_user_square_rounded,
  'user-star': icon_user_star,
  'users': icon_users,
  'video': icon_video,
  'window-maximize': icon_window_maximize,
  'woman': icon_woman,
  'world': icon_world,
  'x': icon_x,
  'zoom-in': icon_zoom_in,
  'zoom-out': icon_zoom_out,
} as const

export type TablerIconName = keyof typeof tablerRegistry
