/**
 * Parses Figma MCP metadata XML and generates icon manifests + asset registries.
 * Source: .scripts/figma-metadata/*.xml (refresh via Figma MCP get_metadata per page)
 *
 * Figma file: u1kcWn7lev6qcjJnUSbOMk (libreria-Iconos)
 */
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const META_DIR = path.join(__dirname, 'figma-metadata')
const MANIFEST_DIR = path.join(ROOT, 'src/shared/icons/manifest')
const ASSETS_DIR = path.join(ROOT, 'src/assets/icons')
const REGISTRY_DIR = path.join(ROOT, 'src/shared/icons/registry')

const FIGMA_FILE_KEY = 'u1kcWn7lev6qcjJnUSbOMk'

const FAMILY_FILES = {
  'iconsax-outline': 'iconsax-outline.xml',
  'iconsax-bold': 'iconsax-bold.xml',
  tabler: 'tabler.xml',
  lucide: 'lucide.xml'
}

const SYMBOL_RE = /<symbol\s+id="([^"]+)"\s+name="([^"]+)"/g

const normalizeRegistryName = (rawName, family) => {
  let name = rawName
    .trim()
    .replace(/\s+/g, '-')
    .replace(/\/\d+xl$/i, '')
    .replace(/\s+\d+$/g, '')
    .toLowerCase()

  if (family === 'iconsax-bold') {
    name = name.replace(/-bold$/i, '')
  }

  if (family === 'lucide') {
    name = name.toLowerCase()
  }

  return name
}

const parseSymbolsFromXml = (xml, family) => {
  const entries = new Map()
  let match

  while ((match = SYMBOL_RE.exec(xml)) !== null) {
    const [, nodeId, rawName] = match
    const name = normalizeRegistryName(rawName, family)
    if (!name || name === 'frame') continue

    if (!entries.has(name)) {
      entries.set(name, { name, nodeId, figmaName: rawName })
    }
  }

  return [...entries.values()].sort((a, b) => a.name.localeCompare(b.name))
}

const listExportedSvgs = (family) => {
  const dir = path.join(ASSETS_DIR, family)
  if (!fs.existsSync(dir)) return new Set()
  return new Set(
    fs
      .readdirSync(dir)
      .filter((f) => f.endsWith('.svg'))
      .map((f) => f.replace(/\.svg$/, ''))
  )
}

const generateRegistryFile = (family, entries, exported) => {
  const withAssets = entries.filter((e) => exported.has(e.name))
  const lines = [
    `/** Auto-generated by syncFigmaIconManifest.js — ${family} */`,
    `/** Catalog: ${entries.length} icons from Figma · Assets on disk: ${withAssets.length} */`,
    ''
  ]

  if (withAssets.length === 0) {
    lines.push(`export const ${toRegistryVar(family)} = {} as const`, '')
    lines.push(`export type ${toTypeName(family)} = keyof typeof ${toRegistryVar(family)}`, '')
    return lines.join('\n')
  }

  for (const { name } of withAssets) {
    lines.push(`import ${toImportId(name)} from '../../../assets/icons/${family}/${name}.svg'`)
  }
  lines.push('')
  lines.push(`export const ${toRegistryVar(family)} = {`)
  for (const { name } of withAssets) {
    lines.push(`  '${name}': ${toImportId(name)},`)
  }
  lines.push('} as const', '')
  lines.push(`export type ${toTypeName(family)} = keyof typeof ${toRegistryVar(family)}`, '')
  return lines.join('\n')
}

const toRegistryVar = (family) =>
  ({
    'iconsax-outline': 'iconsaxOutlineRegistry',
    'iconsax-bold': 'iconsaxBoldRegistry',
    tabler: 'tablerRegistry',
    lucide: 'lucideRegistry'
  }[family])

const toTypeName = (family) =>
  ({
    'iconsax-outline': 'IconsaxOutlineIconName',
    'iconsax-bold': 'IconsaxBoldIconName',
    tabler: 'TablerIconName',
    lucide: 'LucideIconName'
  }[family])

const toImportId = (name) => {
  const safe = name.replace(/[^a-zA-Z0-9]/g, '_')
  return `icon_${safe}`
}

const generateCatalogTs = (catalog) => {
  const lines = [
    '// Auto-generated DO NOT EDIT',
    `export const FIGMA_ICON_FILE_KEY = '${FIGMA_FILE_KEY}' as const`,
    '',
    'export type IconCatalogEntry = {',
    '  name: string',
    '  nodeId: string',
    '  figmaName: string',
    '  hasAsset: boolean',
    '}',
    '',
    'export const iconCatalog = {'
  ]

  for (const [family, entries] of Object.entries(catalog)) {
    lines.push(`  '${family}': [`)
    for (const entry of entries) {
      lines.push(
        `    { name: '${entry.name}', nodeId: '${entry.nodeId}', figmaName: ${JSON.stringify(entry.figmaName)}, hasAsset: ${entry.hasAsset} },`
      )
    }
    lines.push('  ],')
  }

  lines.push('} as const', '')
  lines.push('export type IconCatalogFamily = keyof typeof iconCatalog', '')
  return lines.join('\n')
}

const run = () => {
  fs.mkdirSync(MANIFEST_DIR, { recursive: true })
  Object.values(FAMILY_FILES).forEach((file) => {
    const filePath = path.join(META_DIR, file)
    if (!fs.existsSync(filePath)) {
      console.warn(`⚠️  Missing metadata: ${filePath}`)
    }
  })

  const catalog = {}

  for (const [family, file] of Object.entries(FAMILY_FILES)) {
    const filePath = path.join(META_DIR, file)
    if (!fs.existsSync(filePath)) continue

    const xml = fs.readFileSync(filePath, 'utf-8')
    const entries = parseSymbolsFromXml(xml, family)
    const exported = listExportedSvgs(family)

    const manifest = entries.map((e) => ({
      ...e,
      family,
      fileKey: FIGMA_FILE_KEY,
      hasAsset: exported.has(e.name)
    }))

    catalog[family] = manifest

    fs.writeFileSync(path.join(MANIFEST_DIR, `${family}.json`), JSON.stringify(manifest, null, 2))

    const registryContent = generateRegistryFile(family, entries, exported)
    fs.writeFileSync(path.join(REGISTRY_DIR, `${family}.registry.ts`), registryContent)

    console.info(`✓ ${family}: ${entries.length} names · ${exported.size} SVG assets`)
  }

  fs.writeFileSync(path.join(MANIFEST_DIR, 'catalog.ts'), generateCatalogTs(catalog))

  const indexContent = `// Auto-generated DO NOT EDIT
export { iconsaxOutlineRegistry } from './iconsax-outline.registry'
export { iconsaxBoldRegistry } from './iconsax-bold.registry'
export { tablerRegistry } from './tabler.registry'
export { lucideRegistry } from './lucide.registry'

import { iconsaxOutlineRegistry } from './iconsax-outline.registry'
import { iconsaxBoldRegistry } from './iconsax-bold.registry'
import { tablerRegistry } from './tabler.registry'
import { lucideRegistry } from './lucide.registry'
import type { IconRegistryMap } from '../types'

export const iconRegistry: IconRegistryMap = {
  'iconsax-outline': iconsaxOutlineRegistry,
  'iconsax-bold': iconsaxBoldRegistry,
  tabler: tablerRegistry,
  lucide: lucideRegistry
}
`
  fs.writeFileSync(path.join(REGISTRY_DIR, 'index.ts'), indexContent)

  console.info('✅ Icon manifest synced')
}

run()
