/**
 * Bridge: maps Figma catalog names → existing assets in src/assets (pre-export).
 * Shrinks as SVGs are exported to src/assets/icons/{family}/ via yarn sync:icons:export
 */
import {
  Add2,
  ArrowDown2,
  ArrowLeft2,
  ArrowRight2,
  ArrowSwapVertical,
  Bell,
  Briefcase,
  Broom,
  Buildings2,
  Calendar1,
  Check,
  Close,
  CoinBlackOutline,
  DocumentText,
  Edit,
  Ellipsis,
  Export3,
  EyeSlash,
  FileDownloadLinearBlack,
  FilterIcon,
  HeadsetBlackOutline,
  Home2,
  Id,
  Location,
  Lock,
  LogoutBlackOutline,
  MagicStarBlackOutline,
  Messages2BlackOutline,
  Notification,
  People,
  QuestionCircle,
  Refresh,
  SearchNormal1,
  Setting2,
  Share,
  SmallClose,
  SortIcon,
  Star,
  Tag,
  Trash,
  User,
  Users,
  BookBlueBold,
  BriefcaseBlueBold,
  DocTextBlueBold,
  DollarCircleBlueBold,
  GridBlueBold,
  HomeBlueBold,
  ImageBlueBold,
  InfoCircleBlueBold,
  LocationBlueBold,
  PeopleBlueBold,
  SettingBlueBold,
  Share2Bold,
  TaskBlueBold,
  TickCircleGreenBold,
  UserSearchBlueBold,
  UrgentYellowBold,
  WarningYellowBold
} from '@constants/icons.constants'
import type { IconFamily } from './types'

export const legacyIconBridge: Partial<Record<IconFamily, Record<string, string>>> = {
  'iconsax-outline': {
    add: Add2,
    'arrow-down': ArrowDown2,
    'arrow-left': ArrowLeft2,
    'arrow-right': ArrowRight2,
    'arrow-swap-vertical': ArrowSwapVertical,
    bell: Bell,
    briefcase: Briefcase,
    broom: Broom,
    buildings: Buildings2,
    calendar: Calendar1,
    check: Check,
    close: Close,
    'close-small': SmallClose,
    coin: CoinBlackOutline,
    'document-text': DocumentText,
    edit: Edit,
    ellipsis: Ellipsis,
    export: Export3,
    'eye-slash': EyeSlash,
    filter: FilterIcon,
    headset: HeadsetBlackOutline,
    home: Home2,
    location: Location,
    lock: Lock,
    logout: LogoutBlackOutline,
    'magic-star': MagicStarBlackOutline,
    messages: Messages2BlackOutline,
    notification: Notification,
    people: People,
    'question-circle': QuestionCircle,
    refresh: Refresh,
    search: SearchNormal1,
    setting: Setting2,
    share: Share,
    sort: SortIcon,
    tag: Tag,
    trash: Trash,
    user: User
  },
  'iconsax-bold': {
    book: BookBlueBold,
    briefcase: BriefcaseBlueBold,
    'document-text': DocTextBlueBold,
    'dollar-circle': DollarCircleBlueBold,
    grid: GridBlueBold,
    home: HomeBlueBold,
    image: ImageBlueBold,
    info: InfoCircleBlueBold,
    location: LocationBlueBold,
    people: PeopleBlueBold,
    setting: SettingBlueBold,
    share: Share2Bold,
    task: TaskBlueBold,
    'tick-circle': TickCircleGreenBold,
    'user-search': UserSearchBlueBold,
    urgent: UrgentYellowBold,
    warning: WarningYellowBold
  },
  tabler: {
    'file-download': FileDownloadLinearBlack,
    id: Id,
    star: Star,
    users: Users
  }
}
